src/Foundation/User/rendering/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Okta.AspNetCore;

namespace Mvp.Foundation.Users.Rendering.Controllers
{
    public class UserController : Controller
    {
        public IActionResult SignIn()
        {
            // return View();

            if (!HttpContext.User.Identity.IsAuthenticated)
            {
                var properties = new AuthenticationProperties
                {
                    RedirectUri = "/"
                };

                return Challenge(properties, OktaDefaults.MvcAuthenticationScheme);
            }

            return Redirect("/");
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult SignIn([FromForm]string sessionToken)
        //{
        //    if (!HttpContext.User.Identity.IsAuthenticated)
        //    {
        //        var properties = new AuthenticationProperties();
        //        properties.Items.Add("sessionToken", sessionToken);
        //        properties.RedirectUri = "/";

        //        return Challenge(properties, OktaDefaults.MvcAuthenticationScheme);
        //    }

        //    return Redirect("/");
        //}

        public IActionResult Claims()
        {
            // var userClaims = HttpContext.User.Claims;

            return View();
        }

        [HttpGet]
        public IActionResult SignOut()
        {
            return new SignOutResult(
                new[]
                {
                     OktaDefaults.MvcAuthenticationScheme,
                     CookieAuthenticationDefaults.AuthenticationScheme,
                },
                new AuthenticationProperties { RedirectUri = "/" });
        }
    }
}

src/Foundation/User/rendering/Views/Shared/Components/SignIn.cshtml
@using Mvp.Foundation.User.Extensions

@if (User.Identity.IsAuthenticated)
{
    <ul class="nav navbar-nav">
        <li>
            <span class="nav-item nav-link">
                Hello, @User.Identity.Name
                <a asp-controller="User" asp-action="SignOut">Sign Out</a>
            </span>

        </li>
        @*<li><a class="nav-item nav-link" asp-controller="User" asp-action="Claims" id="profile-button">
            @Html.GravatarImage(
              Html.GetUserEmail(),
              size: 32,
              defaultImage: GravatarHtmlHelper.DefaultImage.MysteryMan,
              rating: GravatarHtmlHelper.Rating.PG,
              cssClass: "gravatar img-responsive")
            Profile</a></li>*@
        @*<li>
                <form class="form-inline" asp-controller="User" asp-action="SignOut" method="post">
                    <button type="submit" class="nav-link btn btn-link" id="logout-button" id="profile-button">Sign Out</button>
                </form>
            </li>*@
    </ul>
}
else
{
    <ul class="nav navbar-nav">
        <li><a class="nav-item nav-link" asp-controller="User" asp-action="SignIn" id="login-button">Sign In</a></li>
    </ul>
}

src/Foundation/User/rendering/Views/User/Claims.cshtml
@using System.Security.Claims;

<h1>Claims</h1>

<div style="margin:20px">
@foreach (var claim in ((ClaimsIdentity)User.Identity).Claims)
{
    <dt title="@claim.Type">@claim.Type</dt>
    <dd>@claim.Value</dd>
}
</div>